// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlite

import (
	"database/sql"
)

type Department struct {
	ID   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type Employee struct {
	ID           string         `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	Email        string         `db:"email" json:"email"`
	Password     string         `db:"password" json:"password"`
	DepartmentID int64          `db:"department_id" json:"department_id"`
	Salary       int64          `db:"salary" json:"salary"`
	DirectorID   sql.NullString `db:"director_id" json:"director_id"`
	EntryAt      sql.NullTime   `db:"entry_at" json:"entry_at"`
	LeavedAt     sql.NullTime   `db:"leaved_at" json:"leaved_at"`
	UpdateAt     sql.NullTime   `db:"update_at" json:"update_at"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
}

type Leave struct {
	ID            int64        `db:"id" json:"id"`
	RequisitionID int64        `db:"requisition_id" json:"requisition_id"`
	StartAt       sql.NullTime `db:"start_at" json:"start_at"`
	EndAt         sql.NullTime `db:"end_at" json:"end_at"`
}

type LeaveRequisition struct {
	ID         int64          `db:"id" json:"id"`
	TypeID     int64          `db:"type_id" json:"type_id"`
	Status     int64          `db:"status" json:"status"`
	Reason     string         `db:"reason" json:"reason"`
	StartAt    sql.NullTime   `db:"start_at" json:"start_at"`
	EndAt      sql.NullTime   `db:"end_at" json:"end_at"`
	DockRate   sql.NullInt64  `db:"dock_rate" json:"dock_rate"`
	EmployeeID sql.NullString `db:"employee_id" json:"employee_id"`
	DirectorID sql.NullString `db:"director_id" json:"director_id"`
	UpdateAt   sql.NullTime   `db:"update_at" json:"update_at"`
	CreatedAt  sql.NullTime   `db:"created_at" json:"created_at"`
}

type LeaveType struct {
	ID        int64        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Status    int64        `db:"status" json:"status"`
	DockRate  int64        `db:"dock_rate" json:"dock_rate"`
	UpdateAt  sql.NullTime `db:"update_at" json:"update_at"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type PaidLeave struct {
	ID         int64        `db:"id" json:"id"`
	EmployeeID string       `db:"employee_id" json:"employee_id"`
	Total      int64        `db:"total" json:"total"`
	Use        int64        `db:"use" json:"use"`
	Year       string       `db:"year" json:"year"`
	UpdateAt   sql.NullTime `db:"update_at" json:"update_at"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
}
